#!/bin/bash
#############################################################################################
###########                                                                       ###########
######                                                                                 ######
##                                                                                         ##
# \author       Luciano Augusto Kruk                                                        #
# \web          www.kruk.eng.br                                                             #
#                                                                                           #
# \description  Shows you the largest objects in your repo's pack file. Written for osx.    #
#                                                                                           #
# \see http://stubbisms.wordpress.com/2009/07/10/.....                                      #
#                     ...git-script-to-show-largest-pack-objects-and-trim-your-waist-line/  #
# \original-author Antony Stubbs                                                            #
# \adapted by \luciano \kruk                                                                #
#                                                                                           #
# \copyright    Please keep this head when you distribute this script.                      #
##                                                                                         ##
######                                                                                 ######
###########                                                                       ###########
#############################################################################################

#set -x 

# temp file:
tempfile=`sh_uniqfile .`

# get full list now:
git rev-list --all --objects > $tempfile

# nothing to do if there is no IDX file:
[ `find .git | grep "pack-.*idx$" | wc -l` = 0 ] && { echo "No .idx file available. Nothing to do."; rm -f $tempfile; exit -1; }

# list all objects including their size, sort by size, take top
# git verify-pack output format:
# [ SHA1 type size size-in-pack-file offset-in-packfile ]

echo "All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file."
git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head -n100 | \
	while read sha type size size_in_pack offset; \
do
	if false; then
		echo "sha = $sha"
		echo "type = $type"
		echo "size = $size"
		echo "size_in_pack = $size_in_pack"
		echo "offset = $offset"
	fi

	# extract the size in bytes
	size_in_kB=$(($size/1024))
	#echo "size_in_kB = $size_in_kB [kB]"

	# find the objects location in the repository tree
	other=`cat $tempfile | grep $sha | sed 's/^[[:graph:]]*[[:blank:]]*//'`
	#echo "other = $other"

	#lineBreak=`echo -e "\n"`
	echo "${size_in_kB} [kB],'$other'"
done | column -t -s ","
rm -f $tempfile

#############################################################################################
