#!/bin/bash
#############################################################################################
###########                                                                       ###########
######                                                                                 ######
##                                                                                         ##
# \author       Luciano Augusto Kruk                                                        #
# \web          www.kruk.eng.br                                                             #
#                                                                                           #
# \description  This script removes strong shadows from scanned images.                     #
#                                                                                           #
# \copyright    Please keep this head when you distribute this script.                      #
##                                                                                         ##
######                                                                                 ######
###########                                                                       ###########
#############################################################################################

if [ $# -ne 1 -a $# -ne 2 ]; then
    echo
    echo "USAGE:"
    echo "    sh_IM_shadow <input_image> [output_image]"
    echo
    exit -1
fi

if [ $# -eq 1 ]; then
    new=`basename "$1"`
    new=`echo "$new" | sed 's/\..\{1,4\}$/-shadow&/'`
else
    new="$2"
fi

convert "$1" \( -clone 0 -colorspace Gray -blur 0x100 \) +swap -compose divide -composite "$new"

#############################################################################################
