#!/bin/bash
#############################################################################################
###########                                                                       ###########
######                                                                                 ######
##                                                                                         ##
# \author       Luciano Augusto Kruk                                                        #
# \web          www.kruk.eng.br                                                             #
#                                                                                           #
# \description  This script converts a file encoded with iso8859-1 to a with utf-8.         #
#               The original file is removed.                                               #
#                                                                                           #
# \copyright    Please keep this head when you distribute this script.                      #
##                                                                                         ##
######                                                                                 ######
###########                                                                       ###########
#############################################################################################

# Este script converte arquivos textos do formato ISO-8859-1 para
# o formato UTF-8.

if [ $# -eq 0 ]; then
    echo
    echo "Usage:"
    echo "   `basename $0` [file-iso8859-1-encoded]"
    echo
    exit -1
fi

TMP=`sh_uniqfile /tmp/`
while [ $# -gt 0 ]; do
	iconv -f iso88591 -t utf8 -o $TMP "$1"
	mv -v $TMP "$1"
	shift
done

