#!/bin/bash
#############################################################################################
###########                                                                       ###########
######                                                                                 ######
##                                                                                         ##
# \author       Luciano Augusto Kruk                                                        #
# \web          www.kruk.eng.br                                                             #
#                                                                                           #
# \description  This script converts SVG files to PDF files.                                #
#                                                                                           #
# \copyright    Please keep this head when you distribute this script.                      #
##                                                                                         ##
######                                                                                 ######
###########                                                                       ###########
#############################################################################################

if [ $# -eq 0 ]; then
    echo
    echo "Usage:"
    echo "   `basename $0` <svg-file-1.svg> [svg-file-2.svg ...]"
    echo
    exit -1
fi

[ "`which inkscape`x" = "x" ] && { echo "'inkscape' NOT found! aborting..."; exit -1; }
[ "`which epstopdf`x" = "x" ] && { echo "'epstopdf' NOT found! aborting..."; exit -1; }

while [ $# -gt 0 ]; do
    suf=`echo $1 | sed 's/^.*\.//'`
    base=`basename $1 .$suf`
    #echo "suf = $suf; base = $base"
    #inkscape "$1" -D -A "./$base.pdf" 2&> /dev/null
	
    # 1) version before 2017.03.28
	#= inkscape "$1" -D -T -B --verb=ObjectRotate90 -E "./$base.eps"

    # 2) version after 2017.03.28
	inkscape "$1" -D -T --verb=ObjectRotate90 -E "./$base.eps"

    epstopdf --nocompress "$base.eps"
	rm -fv "$base.eps"

    # 3) another possibility, when the other fail:
    #= inkscape "$1" --export-pdf="$base.pdf"


    if [ $? -eq 0 ]; then
        echo "File ./$base.pdf created. Done!"
    fi
    shift
done

#############################################################################################
