#!/bin/bash
#############################################################################################
###########                                                                       ###########
######                                                                                 ######
##                                                                                         ##
# \author       Luciano Augusto Kruk                                                        #
# \web          www.kruk.eng.br                                                             #
#                                                                                           #
# \description  This script converts a file encoded with utf-8 to a iso8859-1.              #
#               The original file is removed.                                               #
#                                                                                           #
# \copyright    Please keep this head when you distribute this script.                      #
##                                                                                         ##
######                                                                                 ######
###########                                                                       ###########
#############################################################################################

if [ $# -eq 0 ]; then
    echo
    echo "Usage:"
    echo "   `basename $0` [file-utf8-encoded]"
    echo
    exit -1
fi

TMP=`sh_uniqfile /tmp/`

while [ $# -gt 0 ]; do
	iconv -t iso88591 -f utf8 -o $TMP "$1"
	mv -v $TMP "$1"
	shift
done

#############################################################################################
